version: '3.8'

# 서비스 이름 (예: hellojenkins-web-dev 또는 hellojenkins-web-main)
services:
  SERVICE_NAME_PLACEHOLDER:
    # 이미지 이름 (예: hellojenkins-web-dev:latest)
    image: IMAGE_NAME_PLACEHOLDER
    
    # 컨테이너 이름 (서비스 이름과 동일하게 설정)
    container_name: SERVICE_NAME_PLACEHOLDER

    # ports: 호스트 포트:컨테이너 포트
    # 호스트 포트는 Jenkinsfile에서 DEPLOY_PORT 변수로 대체됩니다.
    ports:
      - "HOST_PORT_PLACEHOLDER:80"
    
    restart: always